version: '3.9'

services: 
    # MongoDB service
    mongo_db:
        container_name: db_container
        image: mongo:latest
        restart: always
        ports:
            - 2717:27017
        volumes:
            - mongo_db:/data/db

    # Node API servcie
    api:
        build: .
        ports:
            - 3000:3000
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment: 
            PORT: 3000
            MONGODB_URL_DEV: mongodb://mongo_db:27017/librarian
            MONGODB_URL_TEST: mongodb://mongo_db:27017/librarian-test
        depends_on: 
            - mongo_db

volumes:
    mongo_db: {}